#!/usr/bin/env python

import wx, functools, event_handlers
from ObjectListView import ColumnDefn

# Filter deprecation warnings from ObjectListView so that they don't
# trigger error log messages on Windows
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning, module='ObjectListView')

import utils

from LogWindow import open_log_window
from ProjectsWindow import ProjectsWindow

app = wx.App(False)

class MainMenuBar(wx.MenuBar):
    def __init__(self, parent):
        wx.MenuBar.__init__(self)
        self.parent = parent

        file_menu = wx.Menu()
        open_menu_item = file_menu.Append(
            wx.ID_ANY, "&Open .sav ...", "Open a .sav file")

        self.Bind(wx.EVT_MENU,
                  functools.partial(
                      event_handlers.open_sav,
                      main_window=parent,
                      projects_window=parent.songs_window),
                  open_menu_item)

        self.Append(file_menu, "&File")

        help_menu = wx.Menu()
        log_window_menu_item = help_menu.Append(
            wx.ID_ANY, "Show Console &Log ...", "Show the Console Log window")

        self.Bind(wx.EVT_MENU,
                  functools.partial(open_log_window, main_window=parent),
                  log_window_menu_item)

        self.Append(help_menu, "&Help")

class MainWindow(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(
            self, None, wx.ID_ANY, "Little Sound MC", size=(600,400),
            style=wx.SYSTEM_MENU | wx.CAPTION | wx.CLOSE_BOX | wx.CLIP_CHILDREN)

        self.sav_obj = None

        panel = wx.Panel(self)
        self.songs_window = ProjectsWindow(panel)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.songs_window, 1, flag=wx.ALL|wx.EXPAND, border=10)

        panel.SetSizer(sizer)

        self.SetMenuBar(MainMenuBar(self))

        self.Bind(wx.EVT_CLOSE, self.handle_close)

        # Display
        self.Layout()
        self.Show()

    def handle_close(self, event):
        try:
            self.songs_window.handle_close(event)
        finally:
            self.Destroy()

    def set_sav(self, sav_obj):
        self.sav_obj = sav_obj
        self.songs_window.handle_sav_loaded(sav_obj)
        self.songs_window.save_sav_button.Enable()

    def get_sav(self):
        return self.sav_obj

    def update_models(self):
        pass


starting_window = MainWindow()

app.MainLoop()
