"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['LSMC']

OPTIONS = {'argv_emulation': True,
           'site_packages': True,
           'iconfile': 'icon.icns'}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
